language: node_js
node_js:
    - "12"
script:
- |
  node -v
  npm -v
  npm i
  npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: main